language: r
cache: packages

os: 
  - osx
  - linux

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - rsetienne/PBD/PBD

after_success:
  - Rscript -e "ribir::is_on_appveyor()"
  - Rscript -e "ribir::is_on_travis()"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'goodpractice::gp()'; fi
