language: r
cache: packages

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - rsetienne/PBD/PBD

after_success:
  - Rscript -e "ribir::is_on_travis()"
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "covr::codecov()"
  - Rscript -e "goodpractice::gp()"
