context("cat_debug_info")

test_that("cat_debug_info use", {
  cat_debug_info(1)
  cat_debug_info(2)
  cat_debug_info(3)
  cat_debug_info(4)
  cat_debug_info(5)
  cat_debug_info(6)
  cat_debug_info(7)
  cat_debug_info(8)
  cat_debug_info(9)
  cat_debug_info(10)
  cat_debug_info(11)
  cat_debug_info(12)
  cat_debug_info(13)
  cat_debug_info(14)
})
